apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: analytics-service:latest #192.168.5.4:5500/analytics-service  
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        env:
        - name: DATABASE_URL
          value: "postgresql://admin:DevTeam+1379@postgres:5432/orders"  # Update with your DB service
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8010"  # Update with your Auth service URL
        - name: ADMINKUBES_SERVICE_URL
          value: "http://adminkubes-service:8030"  # Update with your AdminKubes service URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"