apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image: orders-service:latest #192.168.5.4:5500/orders-service  
        imagePullPolicy: Always
        ports:
        - containerPort: 8020
        env:
        - name: DATABASE_URL
          value: "postgresql://admin:DevTeam+1379@postgres:5432/orders"  # Update with your DB service
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8010"  # Update with your Auth service URL
        - name: ADMINKUBES_SERVICE_URL
          value: "http://adminkubes-service:8030"  # Update with your AdminKubes service URL
        - name: ANALYTICS_SERVICE_URL
          value: "http://analytics-service:8090"  # Update with your Analytics service URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"