apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders-service
  ports:
  - port: 8020
    targetPort: 8000
  type: ClusterIP  # Or LoadBalancer/Ingress for external access