apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminkubes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminkubes-service
  template:
    metadata:
      labels:
        app: adminkubes-service
    spec:
      serviceAccountName: my-app-sa
      containers:
      - name: adminkubes-service
        image: adminkubes-service:latest #192.168.5.4:5500/adminkubes-service  
        imagePullPolicy: Never #Always
        ports:
        - containerPort: 8030
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
