apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest  #192.168.5.4:5500/auth-service  
        imagePullPolicy: Always
        ports:
        - containerPort: 8010
        env:
        - name: DATABASE_URL
          value: "postgresql://admin:DevTeam+1379@postgres:5432/orders"  # Update with your DB service
        - name: SECRET_KEY
          value: "experimento2UAndes"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30"
        - name: ALGORITHM
          value: "HS256"
        - name: ANALYTICS_SERVICE_URL
          value: "http://analytics-service:8090"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"