apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      labels:
        app: apigateway-service
    spec:
      containers:
      - name: apigateway-service
        image: apigateway-service:latest #192.168.5.4:5500/apigateway-service 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8040
        env:
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8010"  # Update with your Auth service URL
        - name:  ADMINKUBES_SERVICE_URL
          value: "http://adminkubes-service:8030"  # Update with your AdminKubes service URL
        - name: ORDERS_SERVICE_URL
          value: "http://orders-service:8000"  # Update with your Orders service URL
        - name: ORDERS_PORT
          value: "8000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"