apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:

        - name: pgadmin4
          image: dpage/pgadmin4
          env:
           - name: PGADMIN_DEFAULT_EMAIL
             value: "admin@admin.com"
           - name: PGADMIN_DEFAULT_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: pgadmin-secret
                 key: pgadmin-default-password
           - name: PGADMIN_PORT
             value: "80"
          ports:
            - containerPort: 80
              name: pgadminport
          volumeMounts:
          - mountPath: /var/lib
            name: pgadmin-storage
      volumes:
        - name: pgadmin-storage
          persistentVolumeClaim:
            claimName: pgadmin-pv-claim
---
    kind: PersistentVolume
    apiVersion: v1
    metadata:
      name: pgadmin-pv-volume
      labels:
        type: local
        app: pgadmin
    spec:
      storageClassName: standard
      capacity:
        storage: 5Gi
      accessModes:
        - ReadWriteMany
      hostPath:
        path: "/mnt/data/pgadmin"
---
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: pgadmin-pv-claim
      labels:
        app: pgadmin
    spec:
      storageClassName: standard
      volumeName: pgadmin-pv-volume
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 5Gi
---


apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  selector:
   app: pgadmin
  type: NodePort
  ports:
   - port: 80
     nodePort: 30200
